### ISSUE TITLE
open to major contributions?

### ISSUE THREAD

**Issue by anarcat** [attestra/puppet-pgbackrest#3]
Hi!

I am starting to use pgbackrest at the Tor Project to manage our backups, and I intend to implement a bunch of features on top of this module. Probably nothing shiny with (e.g.) unit tests (sorry!), but I need things like:

1. automatic export/import of stanzas across servers, to have one central server collecting backup configurations from multiple hosts
2. similarly, collect SSH keys configurations across hosts
3. systemd timers to fire up recurring backup jobs and expiration
4. exporter configuration and hooking up with the prometheus module

Depending on how you are open to contributions, I would provide those a pull requests here... But considering those are rather massive changes, I suspect it would take you some time...

For now, I started with a trivial PR (https://github.com/attestra/puppet-pgbackrest/pull/2) to test the waters, let me know if I should keep em coming.

Otherwise I'll be working on my fork in https://github.com/anarcat/puppet-pgbackrest/

thanks!

**Comment by ubellavance** [comment]
Hi, I'm glad to see that you're interested to contribute to this module.  You probably have more knowledge than me on Puppet, so I'll approuver your PRs blindly.  I won't probably be using your enhancements and don't have an environment to test your changes, but if you're OK with that, I'll do my best to make sure your changes are pushed to the Forge.

**Comment by anarcat** [comment]
awesome, thanks for the quick feedback!
